### ISSUE TITLE
Ch7 P.114 line 29 - missing code

### ISSUE THREAD

**Issue by dannysiu392005** [everydayrails/everydayrails-rspec-2017#13]
The code should be
```ruby
expect(json[0]["name"]).to eq "Second Sample Project"
```
instead of 
```ruby
expect(json["name"]).to eq "Second Sample Project"
```

**Comment by ruralocity** [comment]
Please double-check your code. Are you making the second call to the API? The first (line 12) hits `api_projects_path` and the second (line 22) hits `api_project_path(project_id)`. The JSON from the second hit is a single item:

```
{"id"=>2, "name"=>"Second Sample Project", "description"=>"A test project.", "due_on"=>"2017-07-07", "created_at"=>"2017-06-30T12:46:58.591Z", "updated_at"=>"2017-06-30T12:46:58.591Z", "user_id"=>1}
```

**Comment by dannysiu392005** [comment]
Sorry, this is my careless mistake too.

**Comment by ruralocity** [comment]
Thanks for verifying, I'll close this.
