### ISSUE TITLE
Chapter 4 p. 64 testing late status fails

### ISSUE THREAD

**Issue by acandael** [everydayrails/everydayrails-rspec-2017#15]
I implemented the model specs testing the late status of a project on p.64. I cloned the first chapter and followed along for chapter 2,3 and 4. But when I run the spec "is late when the due date is past today" I get this failure message:

Failure/Error: expect(project).to be_late                   │
       expected #<Project id: 1, name: "Project 2", description: 
"Sample project for testing purposes", due_on: "2017-07-04", created_at: "2017-07-05 07:30:40", updated_at: "2017-07-05 07:30:40", user_id: 1> to respond to `late?`

I suppose these test should pass, but I not sure why they are failing.

**Comment by ruralocity** [comment]
Could you paste the code you have for app/models/project.rb and spec/models/project_spec.rb?

**Comment by acandael** [comment]
app/models/project.rb

class Project < ApplicationRecord
  validates :name, presence: true, uniqueness: { scope: :user_id }

  belongs_to :owner, class_name: 'User', foreign_key: :user_id
  has_many :notes
  has_many :tasks
end


spec/models/project_spec.rb

require 'rails_helper'

RSpec.describe Project, type: :model do
  it "does not allow duplicate project names per user" do
    user = User.create(
      first_name: "Joe",
      last_name: "Tester",
      email: "joetester@example.com",
      password: "123456"
    )

    user.projects.create(
      name: "Test Project",
    )

    new_project = user.projects.build(
      name: "Test Project",
    )

    new_project.valid?
    expect(new_project.errors[:name]).to include("has already been taken")
  end

  it "allows two users to share a project name" do
    user = User.create(
      first_name: "Joe",
      last_name: "Tester",
      email: "joetester@example.com",
      password: "123456"
    )

    user.projects.create(
      name: "Test Project",
    )

    other_user = User.create(
      first_name: "Jane",
      last_name: "Tester",
      email: "janetester@example.com",
      password: "123456",
    )

    other_project = other_user.projects.build(
      name: "Test Project",
    )

    expect(other_project).to be_valid
  end

  describe "late status" do
    it "is late when the due date is past today" do
      project = FactoryGirl.create(:project, :due_yesterday)
      expect(project).to be_late
    end

    it "is on time when the due date is today" do
      project = FactoryGirl.create(:project, :due_today)
      expect(project).to_not be_late
    end

    it "is on time when the due date is in the future" do
      project = FactoryGirl.create(:project, :due_tomorrow)
      expect(project).to_not be_late
    end
  end

  it "can have many notes" do
    project = FactoryGirl.create(:project, :with_notes)
    expect(project.notes.length).to eq 5
  end
end

**Comment by ruralocity** [comment]
I think I see what's going on. Your model is missing the `late?` method, just like the test says. I think it's because it's missing on master, so maybe you started there?

You could try to `git merge 01-untested` to get the full application. If you haven't made any changes outside of the `spec` directory, you shouldn't run into any conflicts.

I will update master once the remaining chapters are finished.

**Comment by acandael** [comment]
Hi, I don't think I can do a git merge, because in the meantime I'm already at chapter 5. I could just add the late field to the projects table with a migration, right?

**Comment by ruralocity** [comment]
Great, thanks for letting me know. I'll close this.
