### ISSUE TITLE
Chapter 6 - page 110 - find_button(...).click

### ISSUE THREAD

**Issue by twalpole** [everydayrails/everydayrails-rspec-2017#18]
The text and example appear to imply that only the `find` methods will wait for elements to appear.  The actions methods like `click_button` will also wait since they are implemented as `find(...).click`.  Therefore recommending `find_button('Close').click` over `click_button('Close')` doesn't make sense.

**Comment by ruralocity** [comment]
Thanks, I removed these references from the upcoming maintenance release.

**Comment by ruralocity** [comment]
Fixed in 2017-10-23 maintenance release.
