### ISSUE TITLE
Chapter 7 - page 114: Typo in projects_apis_spec.rb

### ISSUE THREAD

**Issue by Zhao-Andy** [everydayrails/everydayrails-rspec-2017#19]
In the code block for `projects_apis_spec.rb`, on line 6:
```ruby
get projects_apis_path
```

Should be:
```ruby
get api_projects_path
```

**Comment by ruralocity** [comment]
This code is correct as-is. It's what's generated by `bin/rails g rspec:request projects_api`. We don't wind up keeping it.
