### ISSUE TITLE
Chapter 6, page 108: headless option

### ISSUE THREAD

**Issue by hayah** [everydayrails/everydayrails-rspec-2017#20]
`args` is deprecated.
Instead of
`args: ["headless"],`
we can use
`options: Selenium::WebDriver::Chrome::Options.new(args: %w[headless])`

**Comment by ruralocity** [comment]
Thanks, I'm looking into the best way to present this information.

**Comment by ruralocity** [comment]
Fixed for upcoming maintenance release.

**Comment by ruralocity** [comment]
This will be fixed by updating Capybara, so we can use the simplified configs as described in #27. Thanks for the suggestion—this part of the testing stack has evolved a lot in the last few months.
