### ISSUE TITLE
Chapter 8: Typos and Type Issues

### ISSUE THREAD

**Issue by 3DEsprit** [everydayrails/everydayrails-rspec-2017#25]
Everyday Rails Testing with RSpec: September 18th, 2017
format: mobi

## Support Modules

_**8th paragraph, last sentence**_:

_"In other Words, weâ€™re testing project-specific functionality here, not user or login-specific functionality.”_

4th word has unicode characters in place of the apostrophe

_**2nd and 3rd code block after 8th paragraph**_  (1st code block being spec/rails_helper.rb)

_spec/features/projects_feature.spec_ 

should be **spec/features/projects_spec.rb**

## Lazy-loading with let

**_3rd paragraph, 1st sentence:_** 

“To demonstrate, let’s create a model spec for the Task model, since we havenâ€™t done that yet.”

another case of apostrophe being replaced with unicode charcters in  _haven't_

**Comment by ruralocity** [comment]
Hi Dennis, thanks for letting me know about this. I've fixed the issues for the next release (tonight or tomorrow, depending on how quickly the preview files regenerate).

**Comment by ruralocity** [comment]
Released on 2017-10-16.

**Comment by 3DEsprit** [comment]
You are very welcome, and thanks for the updates and replies!
