### ISSUE TITLE
Chapter 6 - specification of Chrome for use with selenium

### ISSUE THREAD

**Issue by twalpole** [everydayrails/everydayrails-rspec-2017#27]
This can just be done with

    Capybara.javascript_driver = :selenium_chrome

or for headless

    Capybara.javascript_driver = :selenium_chrome_headless

**Comment by ruralocity** [comment]
Thanks, the version I was using still required the extra setup to register the drivers. I've updated to support this and will release in the next maintenance release of the book.

**Comment by ruralocity** [comment]
Fixed in 2017-10-23 maintenance release.
