### ISSUE TITLE
Chapter 6 page 98

### ISSUE THREAD

**Issue by twalpole** [everydayrails/everydayrails-rspec-2017#28]
`click_button` has no guarantee that any actions triggered by it will have completed when it returns.  Because of this you should have an expectation after it that verifies/waits until the action has completed.  In the example on page 98 that means moving at least one of the expectations inside the `change` block.  Without that change the test will be flaky with some drivers.

    expect {
        click_link "New Project"
        fill_in "Name", with: "Test Project"
        fill_in "Description", with: "Trying out Capybara"
        click_button "Create Project"
        expect(page).to have_content "Project was successfully created"
        expect(page).to have_content "Test Project"
        expect(page).to have_content "Owner: #{user.name}"
    }.to change(user.projects, :count).by(1)

**Comment by ruralocity** [comment]
Thanks, I wasn't aware of this. Addressed for the upcoming maintenance release.

**Comment by ruralocity** [comment]
Fixed in 2017-10-23 maintenance release.
