### ISSUE TITLE
shoulda-matchers install fails

### ISSUE THREAD

**Issue by electron0zero** [everydayrails/everydayrails-rspec-2017#32]
Solution: See [shoulda-matchers#1057](https://github.com/thoughtbot/shoulda-matchers/issues/1057) for full discussion

-----

**Solution Text**

Yes, we rebased rails-5 and then merged it into master. Sorry for the mess -- it won't happen again!

For anyone else who found this, we fixed this by deleting the revision sha from our Gemfile.lock and re-ran bundle install.

Be advised that we will remove rails-5 at a certain point, so I would recommend switching to master now if you really want to continue being on the bleeding edge :)

-----

It fails with following error log
```
Fetching https://github.com/thoughtbot/shoulda-matchers.git
fatal: Could not parse object '0b2e0da6035b9c45b0430bc6eb9a8bab4aeba50e'.
Git error: command `git reset --hard 0b2e0da6035b9c45b0430bc6eb9a8bab4aeba50e`
in directory
C:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/shoulda-matchers-0b2e0da6035b has
failed.
If this error persists you could try removing the cache directory
'C:/Ruby24-x64/lib/ruby/gems/2.4.0/cache/bundler/git/shoulda-matchers-e04e9ade87805b3667f97d976fd84556605e66f8'

Process finished with exit code 11
```

**Comment by JunichiIto** [comment]
I had the same error, and could install it by running `bundle update shoulda-matchers`.

**Comment by ruralocity** [comment]
See #73. As @JunichiIto mentions, if you run into this, you can update the gem with bundler. Since Rails 5 support is under active development, this will be a moving target for awhile.
