### ISSUE TITLE
Chapter 6 JavaScript Driver

### ISSUE THREAD

**Issue by kevinjbayer** [everydayrails/everydayrails-rspec-2017#33]
I couldn't get :selenium_chrome to work at all with the given instructions. It kept saying the driver couldn't be found. I finally came across the [chromedriver-helper](https://github.com/flavorjones/chromedriver-helper) gem. Followed their instructions and it worked great. Maybe it was just my setup on macOS Sierra, but thought I'd share anyhow.

**Comment by ruralocity** [comment]
Yes, I wasn't aware of chromedriver-helper until after I released the last version. I haven't had any problems installing chromedriver with homebrew, but we just switched a project over from PhantomJS to selenium-webkit at work, and chromedriver-helper worked out well there. I will address this in a future update.

**Comment by ruralocity** [comment]
Released!
