### ISSUE TITLE
Chapter 2 Test::Unit

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/everydayrails-rspec-2017#34]
In Chapter 2, page 17,

> Now that we’ve got RSpec installed, Rails’ stock generators will no longer generate the default Test::Unit files in the test directory

I think Rails generates Minitest files, not Test::Unit.

**Comment by ruralocity** [comment]
You're right, I'll update this in the next maintenance release.

**Comment by ruralocity** [comment]
Released
