### ISSUE TITLE
Chapter 3 Can't read PDF

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/everydayrails-rspec-2017#38]
In Chapter 3, page 40

<img width="1038" alt="screen shot 2018-02-12 at 5 41 22" src="https://user-images.githubusercontent.com/1148320/36078251-66093c1c-0fb7-11e8-84e4-0e5b157b57c2.png">

`Note.search("messag` ...? (Maybe Leanpub's issue)

**Comment by ruralocity** [comment]
Yes, I think this is an issue with Leanpub. I'll watch for this when I generate the next preview copy and talk to them if it's still an issue then.

**Comment by ruralocity** [comment]
I forgot to mention that I tried to fix this by just re-generating the PDF, but it kept the improper formatting. I wound up rewriting the paragraph to work around the formatting issue with Leanpub.
