### ISSUE TITLE
Chapter 8 CONTENT_TYPES hash

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/everydayrails-rspec-2017#45]
Chapter 8, page 135,

> CONTENT_TYPES hash

Why is `CONTENT_TYPES` written in uppercase? Maybe it should be `content_types`.

**Comment by ruralocity** [comment]
I had experimented with setting it as a constant in an earlier version of the tests. Fixed for the next release.

**Comment by ruralocity** [comment]
Released!
