### ISSUE TITLE
Chapter 10 allow_method_chain

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/everydayrails-rspec-2017#55]
Chapter 10, page 180

> First, we're using `allow_method_chain`

`allow_method_chain` should be `receive_method_chain`.

And you wrote "it introduces a couple of new concepts", but `receive_method_chain` is already introduced in chapter 9. Is it new?

**Comment by ruralocity** [comment]
Does the change I pushed up to the book's repo look better?

**Comment by JunichiIto** [comment]
Yes, it looks better 😃

**Comment by ruralocity** [comment]
Released
