### ISSUE TITLE
Chapter 11 `focus: true` or `:focus`

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/everydayrails-rspec-2017#56]
Chapter 11, page 190,

```
scenario "user completes a project", :focus do
```

You used `:focus` instead of `focus: true`, but this style is not described in this book, so readers might be confused. I recommend mentioning about it.

**Comment by JunichiIto** [comment]
FYI,
One of our reviewers said to me he wondered `:focus` option.

**Comment by ruralocity** [comment]
I've fixed this for the next release, and explained that both variations are possible.

**Comment by ruralocity** [comment]
Released
