### ISSUE TITLE
Chapter 11 method `completed?'

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/everydayrails-rspec-2017#57]
Chapter 11, page 192,

You wrote,

>  If that’s the case, then we’d move forward by defining a complete? method on the Project model, and perhaps return whether a given project’s tasks collection is empty or not.

but in a previous sentence

> Is a project complete when all of its tasks are done?

So I feel "whether a given project’s tasks collection is empty or not" should be "whether a given project’s tasks collection are all done or not", but I am not sure.

**Comment by ruralocity** [comment]
I reworded this some, take a look at the commit and let me know what you think.

**Comment by JunichiIto** [comment]
Mmm, that is not my point. Here is what I feel:

> Is a project complete when all of its tasks are done?

With this description, I imagined Project model should have a method like this:

```ruby
class Project
  def complete?
    self.tasks.all?(&:completed?)
  end
end
```

> returning whether a given project's collection of tasks is empty (complete) or not (incomplete).

But with the description above, I imagined Project model should have a method like this:

```ruby
class Project
  def complete?
    self.tasks.empty?
  end
end
```

They are different. So I felt you changed your mind and it confused me. Which idea is correct? And could you change the description according to your idea? (Maybe my English skill is not enough, though)

**Comment by JunichiIto** [comment]
I read this part again, and did not feel strange. So I think this issue is resolved. Please close it. Thank you.
