### ISSUE TITLE
Ch.2, p.33 - Missing spec "no email"

### ISSUE THREAD

**Issue by Zhao-Andy** [everydayrails/everydayrails-rspec-2017#6]
Think you skipped a spec for `user_spec.rb`: "is invalid without an email address". See page 33 to page 34.

Here is my version:
```
  it "is invalid without an email address" do
    user = User.new(
      first_name:   "Joe",
      last_name:    "Tester",
      password:     "dottle-nouveau-pavillion-tights-furze",
    )
    user.valid?
    expect(user.errors[:email]).to include("can't be blank")
  end
```

Also will need to update bottom of page 46.

**Comment by ruralocity** [comment]
Thanks, I'll address this in the next release.

**Comment by ruralocity** [comment]
Fixed in today's release (July 11, 2017). The sample source has the missing test.
