### ISSUE TITLE
Chapter 11 standalone Ruby code?

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/everydayrails-rspec-2017#60]
Chapter 11, page 204,

You wrote:

> In this case, I used controller specs, but in many cases it’s possible to test directly on a model, or maybe even standalone Ruby code.

I cannot imagine "standalone Ruby code" in Rails application. Is it a code in `lib` directory? Please let me know the examples of standalone Ruby code.

**Comment by ruralocity** [comment]
`lib`, or wherever you put code like service objects. I rewrote this to clarify what I mean.

**Comment by ruralocity** [comment]
Released!
