### ISSUE TITLE
More testing resources for Rails: Heading style is correct?

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/everydayrails-rspec-2017#62]
The heading "Ruby Tapas" is displayed in big font, but I am wondering if it is correct.

![screen shot 2018-02-15 at 11 01 52](https://user-images.githubusercontent.com/1148320/36237546-bf36bb2c-123f-11e8-9824-9de0ab293629.png)

**Comment by ruralocity** [comment]
Released!
