### ISSUE TITLE
Chapter 7 project APIs versus projects API?

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/everydayrails-rspec-2017#67]
Chapter 7, page 113,

You wrote:

> in this case, project APIs versus project API

But probably it should be:

> in this case, project APIs versus projects API

**Comment by ruralocity** [comment]
I think what I have is correct—I'm talking about API being pluralized, not project.

**Comment by JunichiIto** [comment]
Thank you for clarification. I understand.
