### ISSUE TITLE
More testing resources for Rails Relish links

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/everydayrails-rspec-2017#68]
More testing resources for Rails, page 212,

The URL https://www.relishapp.com/rspec-rails is not found. It should be https://relishapp.com/rspec/rspec-rails/docs (Perhaps changed?). 

And https://www.relishapp.com/rspec is redirected to https://relishapp.com/rspec .

**Comment by ruralocity** [comment]
Released!
