### ISSUE TITLE
Chapter 1 Time-specific functionality in chapter 10?

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/everydayrails-rspec-2017#69]
Chapter 1, page 6,

You wrote:

> Chapter 10, Testing the Rest, covers testing those parts of our code we haven’t covered yet–things like email, file uploads, time-specific functionality, and external web services.

However I think time-specific functionality testing is not described in the 2017 edition. In my opinion, time-specific functionality testing is often required, so it should be covered in this edition too.

**Comment by ruralocity** [comment]
I'm dropping the reference to time-specific functionality for this version of the book. I may do something in the future when I've used the `travel_to` method in a real application.
