### ISSUE TITLE
master should-matchers Gemfile.lock error

### ISSUE THREAD

**Issue by YaEvan** [everydayrails/everydayrails-rspec-2017#73]
when I run bundle install in master branch,
`Fetching https://github.com/thoughtbot/shoulda-matchers.git
fatal: Could not parse object '0b2e0da6035b9c45b0430bc6eb9a8bab4aeba50e'.`

I remove Gemfile.lock and run again, it works.

the should-matchers old version in Gemfile.lock is
 GIT
  remote: https://github.com/thoughtbot/shoulda-matchers.git
  revision: 0b2e0da6035b9c45b0430bc6eb9a8bab4aeba50e
  branch: rails-5
  specs:
    shoulda-matchers (3.1.2)
      activesupport (>= 4.2.0)

the should-matchers new version in Gemfile.lock is 
GIT
  remote: https://github.com/thoughtbot/shoulda-matchers.git
  revision: 4b160bd19ecca7f97d7ac22dccd5fde9b0da5a9f
  branch: rails-5
  specs:
    shoulda-matchers (3.1.2)
      activesupport (>= 4.2.0)

**Comment by ruralocity** [comment]
Thanks, I updated with `bundle update shoulda-matchers` and will include the result in the next release.

**Comment by ruralocity** [comment]
Released!
