### ISSUE TITLE
Chapter 4 be_success warning

### ISSUE THREAD

**Issue by YaEvan** [everydayrails/everydayrails-rspec-2017#76]
DEPRECATION WARNING: The success? predicate is deprecated and will be removed in Rails 6.0. Please use successful? as provided by Rack::Response::Helpers.

I use be_successful fix it.

**Comment by ruralocity** [comment]
Thanks for noticing this. I believe you'll only get this deprecation warning if testing a Rails 5.2 application. I have no plans to update the book from Rails 5.1 to 5.2 at this time.

**Comment by YaEvan** [comment]
You are right, I update rails from 5.1 to 5.2, thank you for your reply.
