### ISSUE TITLE
Chapter 8 devise feature helper has new way to include

### ISSUE THREAD

**Issue by YaEvan** [everydayrails/everydayrails-rspec-2017#77]
RSpec.configure do |config|
  config.include Devise::Test::IntegrationHelpers, type: :feature
end

helper method changed to "sign_in" and "sign_out"

https://github.com/plataformatec/devise#integration-tests
https://github.com/plataformatec/devise/blob/master/lib/devise/test/integration_helpers.rb

**Comment by ruralocity** [comment]
Thanks, fixed for the next release.

**Comment by ruralocity** [comment]
Released!
